---
title: "Project Proposal"
author: "Aarij Khawaja"
date: '1st Jan, 2019'
output: html_document
---

For the capstone project, I came up with the idea of ceating a Price Prediction Model from an Airbnb listings dataset.
I found this dataset on Kaggle which was posted as a contest conducted by Deloitte. I'm sure this dataset has been
used in the past by several people participating in the contest, but I was really inspired by the simplicity and
relevance of this model. I see it as simple becaus there is only a single response which is price and everything else
is either a predictor or not. It is extremely relevant and I'm sure the company already has a developed algorithm by now
which predicts the price based on the features I will look at and some other factors. It can help Airbnb with revenue
generation as well as be convenient for the hosts when deciding on the list price.

I will start with cleaning my dataset, keep only the relevant variables and get rid of the missing values. Will then
proceed to the exploratory data analysis where I will be using plots and various asumption tests to analyze the 
predictors. After performing the analysis, I will further clean my dataset to only include the most important predictors
and build a model that will predict the price based on the important features. This model can be used in the prediction
of prices for future Airbnb listings.